apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: test
  namespace: kube-system
  labels:
    app: test
spec:
  selector:
    matchLabels:
      name: pod1
  template:
    metadata:
      labels:
        name: pod1
    spec:
      containers:
      - name: test1
        image: registry.access.redhat.com/ubi8/ubi
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]