---
- name: start and enable firewalld
  service:
    name: firewalld
    state: started
    enabled: true

- name: enable masquerade on k3s
  ansible.posix.firewalld:
    masquerade: "yes"
    state: enabled
    permanent: true
  notify: reload firewalld

- name: remove default public services
  ansible.posix.firewalld:
    service: "{{ item }}"
    zone: public
    state: disabled
    permanent: true
  loop:
    - dhcpv6-client
    - cockpit
  notify: reload firewalld

- name: allow ssh from public
  ansible.posix.firewalld:
    service: ssh
    zone: public
    state: enabled
    permanent: true
  notify: reload firewalld

- name: allow 6443/tcp (Kubernetes API) from public
  ansible.posix.firewalld:
    rich_rule: >
      rule family="ipv4" port port="6443" protocol="tcp" accept
    zone: public
    state: enabled
    permanent: true
  when:
    - k3s_role == "server"
  notify: reload firewalld

- name: enable 2379/tcp (Embedded Etcd) from all nodes
  ansible.posix.firewalld:
    rich_rule: >
      rule family="ipv4" source address="{{ item }}"
      port port="2379" protocol="tcp" accept
    permanent: true
    state: enabled
  loop: "{{ __node_ip_addresses | default([k3s_node_cidr], true) }}"
  when:
    - k3s_role == "server"
  notify: reload firewalld

- name: enable 2380/tcp (Embedded Etcd) from all nodes
  ansible.posix.firewalld:
    rich_rule: >
      rule family="ipv4" source address="{{ item }}"
      port port="2380" protocol="tcp" accept
    permanent: true
    state: enabled
  loop: "{{ __node_ip_addresses | default([k3s_node_cidr], true) }}"
  when:
    - k3s_role == "server"
  notify: reload firewalld

- name: enable 8472/udp (Flannel VXLAN) from all nodes
  ansible.posix.firewalld:
    rich_rule: >
      rule family="ipv4" source address="{{ item }}"
      port port="8472" protocol="udp" accept
    permanent: true
    state: enabled
  notify: reload firewalld
  loop: "{{ __node_ip_addresses | default([k3s_node_cidr], true) }}"

- name: enable 10250/tcp (kubelet) from all nodes
  ansible.posix.firewalld:
    rich_rule: >
      rule family="ipv4" source address="{{ item }}"
      port port="10250" protocol="tcp" accept
    permanent: true
    state: enabled
  notify: reload firewalld
  loop: "{{ __node_ip_addresses | default([k3s_node_cidr], true) }}"

- name: enable 9100/tcp (prometheus node exporter) from all nodes
  ansible.posix.firewalld:
    rich_rule: >
      rule family="ipv4" source address="{{ item }}"
      port port="9100" protocol="tcp" accept
    permanent: true
    state: enabled
  notify: reload firewalld
  loop: "{{ __node_ip_addresses | default([k3s_node_cidr], true) }}"

- name: add cluster-cidr to the firewalld trusted zone
  ansible.posix.firewalld:
    source: "{{ k3s_cluster_cidr }}"
    zone: trusted
    permanent: true
    state: enabled
  notify: reload firewalld
- name: add service-cidr to the firewalld trusted zone
  ansible.posix.firewalld:
    source: "{{ k3s_service_cidr }}"
    zone: trusted
    permanent: true
    state: enabled
  notify: reload firewalld

- meta: flush_handlers
