---
- name: check supported os
  assert:
    quiet: true
    that: ansible_os_family in __k3s_supported_os

- name: include os specific vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: check group membership
  assert:
    quiet: true
    that: >
      'servers' in group_names or
      'agents' in group_names

- name: set k3s_role for servers
  set_fact:
    k3s_role: server
    k3s_primary: "{{ groups['servers'][0] == inventory_hostname }}"
  when: "'servers' in group_names"

- name: set k3s_role for agents
  set_fact:
    k3s_role: agent
  when: "'agents' in group_names"

- debug: var=k3s_role

- import_tasks: prereq.yml

- import_tasks: firewall.yml

- import_tasks: selinux.yml

- import_tasks: downloads.yml

- include_tasks: server.yml
  when: k3s_role == "server"

- include_tasks: agent.yml
  when: k3s_role == "agent"
