---
- name: run k3s installer
  block:
    - name: set remote environment for install command
      set_fact:
        __cmd_environment:
          INSTALL_K3S_VERSION: "{{ k3s_installer_version }}"
          INSTALL_K3S_CHANNEL: "{{ k3s_installer_channel }}"
          INSTALL_K3S_BIN_DIR: "{{ __k3s_install_dir }}"
          INSTALL_K3S_EXEC: "{{ k3s_role }}"
          INSTALL_K3S_SKIP_START: "{% if k3s_role == 'server' %}true{% endif %}"
    - name: run k3s installer
      command:
        cmd: "{{ __k3s_download_dir }}/k3s-install.sh"
        creates: "{{ __k3s_install_dir }}/k3s"
      environment: "{{ __cmd_environment }}"
      register: r_cmd_k3s_install


  always:
    - name: create k3s-install.log
      copy:
        dest: "{{ __k3s_download_dir }}/k3s-install.{{ item.type }}.log"
        content: |
          # created by Ansible!
          # k3s install log ({{ item.type}})
          # start: {{ r_cmd_k3s_install.start }}
          # environment:
          {% for k, v in __cmd_environment.items() %}
          {{ k }}={{ v }}
          {% endfor %}
          # log:
          {{ r_cmd_k3s_install[item.type] }}
          # end: {{ r_cmd_k3s_install.end }}
        mode: "0440"
      loop:
        - type: stdout
        - type: stderr
      when: r_cmd_k3s_install.changed | bool
