---
# handlers file for k3s
- name: set firewalld default zone
  command: firewall-cmd --set-default-zone='{{ __k3s_firewalld_default_zone }}'

- name: reload firewalld
  command: firewall-cmd --reload
