---
# tasks/docker.yml

- name: docker - remove old versions of docker
  dnf:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: absent

- name: docker - add docker gpg key
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: docker - add docker repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    owner: root
    group: root
    mode: 0644

- name: docker - install docker
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  register: docker_install

- name: docker - enable and start docker service
  service:
    name: docker
    state: restarted
    enabled: true
  when: docker_install.changed

- name: docker - install pip (python3)
  dnf:
    name: python3-pip
    state: present

- name: docker - install docker using pip
  pip:
    name: docker
    state: present
    executable: pip3

- name: docker - install docker-compose using pip
  pip:
    name: docker-compose
    state: present
    executable: pip3

- name: add {{ vagrant_user }} user to docker group
  user:
    name: "{{ vagrant_user }}"
    groups: docker
    append: true