---
# tasks/molecule.yml

- name: molecule - install requirements for molecule
  dnf:
    name:
      - gcc
      - python3-pip
      - python3-devel
      - openssl-devel
      - python3-libselinux
    state: present
  become: true

- name: molecule - install molecule
  pip:
    name:
      - molecule
      - yamllint
      - ansible-lint
    state: present
