---
namespace: jakemalley
name: k3s
description: A collection of K3S related automation
version: 0.0.1

authors:
  - Jake Malley (https://jakemalley.com)
license:
  - GPL-2.0-or-later

tags:
  - k3s
  - kubernetes

dependencies: {}

readme: README.md
documentation: https://github.com/jakemalley/ansible-collection-k3s
homepage: https://github.com/jakemalley/ansible-collection-k3s
repository: https://github.com/jakemalley/ansible-collection-k3s
issues: https://github.com/jakemalley/ansible-collection-k3s/issues

build_ignore:
  - .DS_Store
